let a = []

let b = a.unshift(1)
let c = a.unshift(22)
let d = a.shift()
let e = a.unshift(3, [4, 5])
let f = a.shift()
let g = a.shift()
let h = a.shift()
console.log(a)
console.log(b)
console.log(c)
console.log(d)
console.log(e)
console.log(f)
console.log(g)
console.log(h)